"""Stage 04 -- turn extracted equations into an executable Python module.

The LaTeX parser lives in stage 02 (``translator.py``).  This module re-exports
that API so ``from translate2python import translate`` still works, and writes
``equations.py`` from ``equations_raw.md``.

Typical use::

    from translate2python import translate
    eq = translate(r"h=1.45 k \\frac{\\tan \\theta}{\\sigma}"
                   r"\\left(\\frac{p}{H}\\right)^{0.985}")
    print(eq.python)          # h = 1.45*k*(p/H)**0.985*tan(theta)/sigma
    print(eq.evaluate(k=1, theta=0.1, sigma=2, p=3, H=4))

Run it with::

    python src/04_translate2python/translate2python.py
    python src/04_translate2python/translate2python.py --source src/01_input/sample_2.md
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Dict, List, Optional, Sequence, Tuple

_SRC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from execusci_paths import add_stages, mirror_to_log, paper_path, stage_dir  # noqa: E402

add_stages("Extract Equations")

from translator import (  # noqa: E402
    Equation,
    LatexParseError,
    MATH_NAMESPACE,
    Parser,
    latex_to_name,
    name_to_latex,
    preprocess,
    tokenize,
    translate,
)

__all__ = [
    "Equation",
    "translate",
    "translate_document",
    "preprocess",
    "tokenize",
    "Parser",
    "generate_module",
    "name_to_latex",
    "latex_to_name",
    "MATH_NAMESPACE",
    "LatexParseError",
    "run_document",
    "run",
]

# Names that the generated Python expressions/functions rely on being in scope.
# NumPy is used so the generated code works on scalars *and* arrays.
_NAMESPACE_IMPORT = (
    "from numpy import (\n"
    "    exp, log, sqrt, sin, cos, tan, sinh, cosh, tanh, pi,\n"
    "    arcsin as asin, arccos as acos, arctan as atan, abs as Abs,\n"
    ")\n"
)

DEFAULT_MODULE = os.path.join(stage_dir("Translate2Python"), "equations.py")
_EXTRACTED = os.path.join(stage_dir("Extract Equations"), "output")
DEFAULT_SOURCE = os.path.join(_EXTRACTED, "equations_raw.md")
DEFAULT_SYMBOLS = os.path.join(_EXTRACTED, "symbols.json")


def translate_document(text: str) -> List[Tuple["RawEquation", Optional[Equation], Optional[str]]]:
    """Translate every equation in a document.

    Returns a list of ``(raw, equation, error)`` triples so callers can report
    on fragments that could not be parsed instead of aborting the whole run.
    """
    from extract_equations import extract_latex_equations

    results = []
    for raw in extract_latex_equations(text):
        try:
            eq = translate(raw.latex, tag=raw.tag)
            results.append((raw, eq, None))
        except LatexParseError as exc:
            results.append((raw, None, str(exc)))
    return results


def generate_module(
    text: str,
    module_doc: str = "",
    descriptions: Optional[Dict[str, str]] = None,
) -> str:
    """Translate all equations in ``text`` and return runnable Python source.

    The returned string is a complete module: NumPy imports followed by one
    function per successfully parsed equation.  Equations that fail to parse are
    recorded as comments so nothing is silently dropped.  ``descriptions`` maps
    symbol names to the paper's wording and is used to document the arguments.
    """
    header = ['"""' + (module_doc or "Auto-generated by ExecuSci translate2python.") + '"""',
              "", _NAMESPACE_IMPORT.rstrip(), "", ""]
    body: List[str] = []
    used_names: Dict[str, int] = {}
    for raw, eq, error in translate_document(text):
        if error is not None or eq is None:
            body.append(f"# Could not translate (Eq. {raw.tag}): {raw.latex}")
            if error:
                body.append(f"#   reason: {error}")
            body.append("")
            continue
        name = eq._default_name()
        # Disambiguate duplicate names (several equations define ``h`` etc.).
        if name in used_names:
            used_names[name] += 1
            name = f"{name}_{used_names[name]}"
        else:
            used_names[name] = 1
        body.append(eq.function_source(name=name, descriptions=descriptions))
        body.append("")
        body.append("")
    return "\n".join(header + body).rstrip() + "\n"


def load_symbol_dictionary(path: str = DEFAULT_SYMBOLS) -> dict:
    """Stage 02's ``symbols.json``, or ``{}`` if that stage has not run."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def descriptions_from(dictionary: dict) -> Dict[str, str]:
    """``name -> description`` for every symbol the paper describes."""
    return {
        name: info["description"]
        for name, info in dictionary.get("symbols", {}).items()
        if info.get("description")
    }


def load_descriptions(path: str = DEFAULT_SYMBOLS) -> Dict[str, str]:
    """``name -> description`` from stage 02, or ``{}`` if it has not run."""
    return descriptions_from(load_symbol_dictionary(path))


def _print_equation(eq, tag=None) -> None:
    label = f"Eq. {tag}" if tag else "Equation"
    print(f"[{label}]")
    print(f"  LaTeX : {eq.latex}")
    print(f"  Python: {eq.python}")
    if eq.inputs:
        print(f"  Inputs: {', '.join(s.name for s in eq.inputs)}")
    print()


def run_document(
    path: str = DEFAULT_SOURCE,
    module_path: str = DEFAULT_MODULE,
    symbols_path: str = DEFAULT_SYMBOLS,
    verbose: bool = True,
) -> int:
    """Translate every equation in ``path`` and write the equations module."""
    if not os.path.exists(path):
        print(f"Error: file not found: {path}", file=sys.stderr)
        return 1
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()

    results = translate_document(text)
    if not results:
        print(f"No equations found in {path}.")
        return 1

    ok = 0
    for raw, eq, error in results:
        if eq is None:
            print(f"[Eq. {raw.tag}]  COULD NOT TRANSLATE")
            print(f"  LaTeX : {raw.latex}")
            print(f"  Reason: {error}\n")
            continue
        ok += 1
        if verbose:
            _print_equation(eq, tag=raw.tag)

    dictionary = load_symbol_dictionary(symbols_path)
    descriptions = descriptions_from(dictionary)
    origin = dictionary.get("source") or os.path.basename(path)
    source = generate_module(
        text,
        module_doc=f"Executable equations extracted from {origin}.",
        descriptions=descriptions,
    )
    with open(module_path, "w", encoding="utf-8") as fh:
        fh.write(source)
    mirror_to_log(module_path)

    print(f"Translated {ok}/{len(results)} equations from {os.path.basename(path)}.")
    if descriptions:
        print(f"Documented arguments using {len(descriptions)} symbol descriptions.")
    print(f"Wrote runnable module to {module_path}.")
    return 0 if ok == len(results) else 1


run = run_document


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Translate extracted LaTeX equations into a Python module."
    )
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE,
        help=f"Document holding the equations (default: {DEFAULT_SOURCE})",
    )
    parser.add_argument(
        "--module",
        default=DEFAULT_MODULE,
        help=f"Generated module path (default: {DEFAULT_MODULE})",
    )
    parser.add_argument(
        "--symbols",
        default=DEFAULT_SYMBOLS,
        help="Stage 02 symbol dictionary used to document arguments.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Only print the summary, not every translated equation.",
    )
    return parser.parse_args(list(argv) if argv is not None else None)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parse_args(argv)
    source = args.source
    if not os.path.exists(source) and source == DEFAULT_SOURCE:
        print(
            f"{os.path.basename(source)} not found -- run stage 02 first. "
            "Falling back to the paper itself.",
            file=sys.stderr,
        )
        source = paper_path()
    return run_document(
        source,
        module_path=args.module,
        symbols_path=args.symbols,
        verbose=not args.quiet,
    )


if __name__ == "__main__":
    raise SystemExit(main())
