"""Stage 03 -- scrape every numeric constant the paper states and name it.

Each scraped value is given the same ASCII symbol name that ``latex2python``
generates for the equations (``\\lambda`` → ``lamda``, ``k_{s}`` → ``k_s``, …),
so the constants drop straight into the functions generated by stage 04.  The
generated module also builds a :class:`sympy.Symbol` for every name, so the
constants can be substituted into the symbolic form of the equations.

Sources
-------
1. **Symbol-keyed tables** (e.g. Table 3, "Material constants and model
   parameters"): header cell → symbol name, value cell → float.
2. **Property tables** (e.g. Table 2, "Material properties"), which are keyed by
   a property name per row and a material per column: ``Thermal conductivity``
   under ``P20`` → ``k`` for material ``P20``.  Temperature-dependent entries
   such as ``-39.082 T + 82532`` are recorded as expressions, not numbers.
3. **Prose** patterns such as ``$h_a$ ... approximately $0.8$``.

Run it with::

    python src/03_scrape_constants/scrape_constants.py
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

_SRC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _SRC not in sys.path:
    sys.path.insert(0, _SRC)

from execusci_paths import LOG, add_stages, mirror_to_log, paper_path, stage_dir  # noqa: E402

add_stages("Latex2Python")

from latex2python import latex_to_name, name_to_latex  # noqa: E402

__all__ = [
    "Constant",
    "extract_constants",
    "extract_tables",
    "generate_constants_module",
    "generate_report",
    "latex_to_name",
    "parse_number",
    "reconcile_names",
    "run",
]

_SCRAPE = stage_dir("Scrape Constants")
DEFAULT_CONSTANTS_PATH = os.path.join(_SCRAPE, "constants.py")
DEFAULT_REPORT_PATH = os.path.join(LOG, os.path.basename(_SCRAPE), "constants.md")

# Tool / material labels that appear in Table 3 headers like ``k_t (H13)``.
_TOOL_ALIASES = {
    "h13": "H13",
    "p20": "P20",
    "cast iron": "CastIron",
    "castiron": "CastIron",
}

# Materials that are not tools but do get their own property column (Table 2).
_MATERIAL_ALIASES = {
    "aa7075": "AA7075",
    "aa7075-t6": "AA7075",
    "specimen": "AA7075",
}

# Parenthetical labels that are descriptive, not tool variants.
_NON_TOOL_LABELS = {"lubricant", "blank", "specimen"}

# Row labels of a property table -> the symbol conventionally used for them.
# ``alpha_t`` (thermal expansion) is deliberately not ``alpha``, which Table 3
# already uses for the solid-contact IHTC model parameter.
_PROPERTY_SYMBOLS: Dict[str, str] = {
    "young's modulus": "E",
    "youngs modulus": "E",
    "elastic modulus": "E",
    "density": "rho",
    "thermal conductivity": "k",
    "specific heat capacity": "c_p",
    "specific heat": "c_p",
    "poisson's ratio": "nu",
    "poissons ratio": "nu",
    "thermal expansion": "alpha_t",
    "ultimate strength": "sigma_U",
    "tensile strength": "sigma_U",
    "surface roughness": "R_a",
    "hardness": "H",
}

# Equation-symbol names treated as thermophysical / contact-body properties.
_MATERIAL_NAMES = set(_PROPERTY_SYMBOLS.values()) | {
    "k_s", "k_t", "k_l", "k_f", "k_w", "R_s", "R_t",
}

# Operating conditions the caller typically supplies (not tabulated properties).
_OPERATING_NAMES = {"P", "p", "t", "T", "delta", "v", "w"}
_OPERATING_DESC_RE = re.compile(
    r"\b(pressure|time|temperature|speed|velocity|load|film thickness|"
    r"sliding|strain rate)\b",
    re.IGNORECASE,
)

# First cell of a property table's header row.
_PROPERTY_HEADERS = {"property", "properties", "parameter", "parameters", "material"}

# Short header words that structure a table rather than name a quantity.
_STRUCTURAL_HEADERS = {
    "no", "value", "values", "unit", "units", "symbol", "test", "id", "ref",
}

# A cell that depends on temperature, e.g. ``-39.082 \mathrm{~T}+82532``.
_TEMPERATURE_RE = re.compile(r"\\mathrm\{[^}]*\bT\b[^}]*\}|(?<![A-Za-z\\])T(?![A-Za-z])")

_MD_TABLE_ROW_RE = re.compile(r"^\|(?P<cells>.+)\|\s*$", re.MULTILINE)
_SEPARATOR_RE = re.compile(r"^[\s:|\-]+$")
_TABLE_CAPTION_RE = re.compile(
    r"(?:^|\n)\s*Table\s+(?P<num>\d+)\s*\n(?P<title>[^\n|]+)?",
    re.IGNORECASE,
)

# Prose: $symbol$ ... approximately|of|=|≈ ... number (optionally in $...$).
# Captions that are material data sheets, not model-constant tables.
_SKIP_CAPTION_RE = re.compile(r"composition|propert(?:y|ies)", re.I)
_KEEP_CAPTION_RE = re.compile(r"constant|parameter", re.I)

# Prose: $symbol$ ... approximately|of|=|≈ ... number (optionally in $...$).
_PROSE_CONST_RE = re.compile(
    r"\$\s*(?P<sym>[^$=]+?)\s*\$"
    r"(?P<bridge>.{0,120}?)"
    r"(?:approximately|approx\.?|of|equal(?:s| to)?|≈|=|:)\s*"
    r"(?:\$\s*)?(?P<val>[0-9][0-9eE+.\-\\mathrm\{\}\s~]*)",
    re.IGNORECASE | re.DOTALL,
)


@dataclass
class Constant:
    """One scraped constant.

    ``value`` is ``None`` only for temperature-dependent material properties,
    whose LaTeX is kept in ``expression`` instead of being turned into a number.
    """

    name: str
    value: Optional[float]
    unit: Optional[str] = None
    variant: Optional[str] = None  # tool or material, e.g. "H13", "AA7075"
    source: str = "table"  # "table" | "prose"
    table: Optional[str] = None  # e.g. "3"
    caption: Optional[str] = None
    source_line: Optional[int] = None
    raw_header: Optional[str] = None
    raw_value: Optional[str] = None
    category: str = "model"  # "model" (Table 3 style) | "material" (Table 2 style)
    label: Optional[str] = None  # property name as printed, e.g. "Young's modulus"
    expression: Optional[str] = None  # LaTeX of a temperature-dependent property
    corrected_from: Optional[str] = None  # name before OCR reconciliation

    @property
    def is_numeric(self) -> bool:
        return self.value is not None


@dataclass
class _MarkdownTable:
    headers: List[str]
    rows: List[List[str]]
    start: int
    table_num: Optional[str] = None
    caption: Optional[str] = None


# --------------------------------------------------------------------------- #
# Number / symbol helpers
# --------------------------------------------------------------------------- #

def parse_number(text: str) -> Optional[float]:
    """Parse a Mathpix / LaTeX numeric cell into a Python float.

    Handles ``3.4e-7``, ``3.4 \\mathrm{e}-7``, ``2.01 e-4``, ``7.85 e 03``.
    """
    if text is None:
        return None
    s = text.strip()
    if not s or s.lower() in {"bal.", "bal", "-", "—", "–"}:
        return None

    # Drop math wrappers and unit fragments so digits remain.
    s = s.replace("$", " ")
    s = re.sub(r"\\mathrm\{([^}]*)\}", r"\1", s)
    s = re.sub(r"\\text\{([^}]*)\}", r"\1", s)
    s = re.sub(r"\\[a-zA-Z]+", " ", s)  # \quad, \times, …
    s = s.replace("{", " ").replace("}", " ").replace("~", " ")
    s = re.sub(r"\s+", " ", s).strip()

    # Scientific: "3.4 e -7" / "3.4e-7" / "2e5"
    m = re.search(
        r"([+-]?\d+(?:\.\d+)?)\s*[eE]\s*([+-]?\d+)",
        s,
    )
    if m:
        try:
            return float(f"{m.group(1)}e{m.group(2)}")
        except ValueError:
            return None

    m = re.search(r"([+-]?\d+(?:\.\d+)?)", s)
    if m:
        try:
            return float(m.group(1))
        except ValueError:
            return None
    return None


def _normalize_tool(label: str) -> Optional[str]:
    key = re.sub(r"\s+", " ", label.strip().lower())
    if key in _NON_TOOL_LABELS:
        return None
    return _TOOL_ALIASES.get(key)


def _split_plain_header(cell: str) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """Read a header cell Mathpix left as plain text, e.g. ``R (J/(K ⋅ mol))``.

    Such a cell only names a constant when it is a one- or two-character symbol
    carrying a unit parenthetical.  Requiring the unit is what separates the
    quantity ``R (J/(K ⋅ mol))`` from the column *labels* a table also has --
    material names (``H13``, ``P20``), element symbols (``Si``, ``Fe``) and
    ordinary words (``Notes``, ``Load (N)``), none of which are constants.
    """
    label, bracket, tail = cell.partition("(")
    label = label.strip()
    if not bracket or not re.fullmatch(r"[A-Za-z][A-Za-z0-9]?", label):
        return None, None, None
    if label.lower() in _STRUCTURAL_HEADERS:
        return None, None, None
    tail = tail.strip()
    if tail.endswith(")"):  # drop only the parenthesis this label opened
        tail = tail[:-1]
    unit = _clean_unit(tail) if tail else None
    if unit in {"-", "—", "–"}:
        unit = None
    return latex_to_name(label), None, unit


def _split_header(cell: str) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """Return ``(symbol_name, tool_variant, unit)`` from a table header cell."""
    raw = cell.strip()
    if not raw:
        return None, None, None

    # Bare text like ``H13``, ``Property``, ``AA7075`` is not a math symbol header.
    # Model-constant headers from Mathpix usually contain ``$`` / ``\`` / ``_``,
    # but a plain letter such as ``R (J/(K ⋅ mol))`` needs no markup at all.
    if not re.search(r"[\\_$]", raw):
        return _split_plain_header(raw)

    # Pure numeric / scientific-notation cells are values, never headers.
    if re.search(r"\d\s*(?:\\mathrm\{e\}|[eE])\s*[+\-]?\s*\d", raw):
        return None, None, None
    if re.fullmatch(r"\$?\s*[+-]?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\s*\$?", raw):
        return None, None, None

    variant: Optional[str] = None
    unit: Optional[str] = None
    work = raw

    # Normalise \left(...\right) before scanning parentheses.
    work = re.sub(r"\\left\s*", "", work)
    work = re.sub(r"\\right\s*", "", work)

    # Tool labels and unit / dimensionless parentheses.
    for m in list(re.finditer(r"\(([^)]+)\)", work)):
        inner = m.group(1).strip()
        tool = _normalize_tool(inner)
        if tool is not None:
            variant = tool
            work = work[: m.start()] + work[m.end() :]
            continue
        if inner.lower() in _NON_TOOL_LABELS or inner in {"-", "—", "–"}:
            work = work[: m.start()] + " " + work[m.end() :]
            continue
        # Unit parenthetical: (\mathrm{~kW}/mK), (m^{-1}), …
        if re.search(r"\\mathrm|kW|[/^]|\\?\b m\b|K\b|-1|~\w", inner, re.I):
            cleaned = re.sub(r"\\mathrm\{([^}]*)\}", r"\1", inner)
            cleaned = re.sub(r"[~$\\\s]", "", cleaned)
            unit = (unit + cleaned) if unit else cleaned
            work = work[: m.start()] + " " + work[m.end() :]

    # Unwrap identity \mathrm{t} inside subscripts — but never \mathrm{e} (sci note).
    work = re.sub(r"\\mathrm\{([A-Za-df-z]+)\}", r"\1", work)

    # Trailing unit fragments still attached: \mathrm{~kW}, ^{-1}, …
    for um in list(re.finditer(r"\\mathrm\{([^}]*)\}", work)):
        content = um.group(1)
        if re.search(r"kW|m|K|[/^~]|-1|\d", content, re.I):
            cleaned = re.sub(r"[~$\\\s]", "", content)
            unit = (unit + cleaned) if unit else cleaned
            work = work[: um.start()] + " " + work[um.end() :]

    work = re.sub(r"\^{[^}]*}", " ", work)
    work = re.sub(r"\^[+\-]?\d+", " ", work)

    work = work.replace("$", " ")
    work = re.sub(r"\\text\{[^}]*\}", " ", work)
    work = re.sub(r"[()]", " ", work)
    work = re.sub(r"\s+", " ", work).strip()
    work = re.sub(r"\s*-\s*$", "", work).strip()

    if not work or work.lower() in {"property", "element"}:
        return None, variant, unit

    name = latex_to_name(work)
    return name, variant, unit or None


# --------------------------------------------------------------------------- #
# Table extraction
# --------------------------------------------------------------------------- #

def extract_tables(text: str) -> List[_MarkdownTable]:
    """Find pipe-style markdown tables and attach nearby ``Table N`` captions."""
    captions: List[Tuple[int, str, str]] = []
    for m in _TABLE_CAPTION_RE.finditer(text):
        title = (m.group("title") or "").strip()
        captions.append((m.start(), m.group("num"), title))

    tables: List[_MarkdownTable] = []
    lines = text.splitlines(keepends=True)
    # Rebuild with absolute offsets.
    offset = 0
    i = 0
    while i < len(lines):
        line = lines[i]
        if not _MD_TABLE_ROW_RE.match(line.rstrip("\n")):
            offset += len(line)
            i += 1
            continue

        block_start = offset
        row_lines: List[str] = []
        while i < len(lines) and _MD_TABLE_ROW_RE.match(lines[i].rstrip("\n")):
            row_lines.append(lines[i].rstrip("\n"))
            offset += len(lines[i])
            i += 1

        parsed_rows: List[List[str]] = []
        for rl in row_lines:
            m = _MD_TABLE_ROW_RE.match(rl)
            if not m:
                continue
            cells = [c.strip() for c in m.group("cells").split("|")]
            # Separator row (| :--- | :--- |).
            if all(_SEPARATOR_RE.match(c.replace(":", "-")) or not c for c in cells):
                continue
            if all(re.fullmatch(r":?-{3,}:?", c.replace(" ", "")) for c in cells if c):
                continue
            parsed_rows.append(cells)

        if len(parsed_rows) < 2:
            continue

        headers = parsed_rows[0]
        data = parsed_rows[1:]
        # Nearest caption before this table.
        table_num = caption = None
        for cap_pos, num, title in reversed(captions):
            if cap_pos < block_start:
                table_num, caption = num, title
                break
        tables.append(
            _MarkdownTable(
                headers=headers,
                rows=data,
                start=block_start,
                table_num=table_num,
                caption=caption,
            )
        )
    return tables


def _line_of(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def _parse_header_row(
    cells: List[str],
) -> List[Tuple[Optional[str], Optional[str], Optional[str], str]]:
    return [(*_split_header(h), h) for h in cells]


def _row_symbol_score(cells: List[str]) -> Tuple[int, int]:
    """Return ``(symbol_hits, numeric_hits)`` for classifying header vs value rows."""
    symbols = 0
    numbers = 0
    for cell in cells:
        if not cell or not cell.strip():
            continue
        name, _, _ = _split_header(cell)
        num = parse_number(cell)
        # A pure number cell is a value; a parseable symbol (even if a number
        # substring exists inside units) counts as a header when named.
        if name is not None and not re.fullmatch(
            r"\$?\s*[+-]?\d+(?:\.\d+)?(?:\s*[eE]\s*[+-]?\d+)?\s*\$?",
            cell.strip(),
        ):
            # Prefer symbol if the cell is clearly math/identifier-heavy.
            if re.search(r"[\\_A-Za-z]", cell):
                symbols += 1
                continue
        if num is not None:
            numbers += 1
        elif name is not None:
            symbols += 1
    return symbols, numbers


def _row_is_header_like(cells: List[str]) -> bool:
    symbols, numbers = _row_symbol_score(cells)
    return symbols > 0 and symbols >= numbers


def _row_is_value_like(cells: List[str]) -> bool:
    symbols, numbers = _row_symbol_score(cells)
    return numbers > 0 and numbers >= symbols


def _emit_row_constants(
    parsed_headers: List[Tuple[Optional[str], Optional[str], Optional[str], str]],
    row: List[str],
    table: _MarkdownTable,
    text: str,
) -> List[Constant]:
    out: List[Constant] = []
    for col, (name, variant, unit, raw_h) in enumerate(parsed_headers):
        if name is None or col >= len(row):
            continue
        raw_v = row[col]
        value = parse_number(raw_v)
        if value is None:
            continue
        out.append(
            Constant(
                name=name,
                value=value,
                unit=unit,
                variant=variant,
                source="table",
                table=table.table_num,
                caption=table.caption,
                source_line=_line_of(text, table.start),
                raw_header=raw_h,
                raw_value=raw_v,
            )
        )
    return out


def _constants_from_table(table: _MarkdownTable, text: str) -> List[Constant]:
    """Pair symbol headers with numeric cells.

    Mathpix often emits "stacked" constant tables as **one** markdown table
    with alternating header / value rows (see Table 3).  Detect that pattern
    instead of treating every non-first row as values for the top header.
    """
    if _is_property_table(table):
        return _constants_from_property_table(table, text)

    if table.caption and _SKIP_CAPTION_RE.search(table.caption):
        if not _KEEP_CAPTION_RE.search(table.caption):
            return []

    # Build the sequence: markdown header row + body rows.
    all_rows: List[List[str]] = [table.headers, *table.rows]
    out: List[Constant] = []
    parsed_headers: Optional[
        List[Tuple[Optional[str], Optional[str], Optional[str], str]]
    ] = None
    symbol_header_blocks = 0

    for row in all_rows:
        if _row_is_header_like(row) and not _row_is_value_like(row):
            parsed_headers = _parse_header_row(row)
            named = sum(1 for n, _, _, _ in parsed_headers if n is not None)
            if named >= max(1, len([c for c in row if c.strip()]) // 2):
                symbol_header_blocks += 1
            else:
                parsed_headers = None
            continue

        if parsed_headers is None:
            continue

        if _row_is_value_like(row):
            out.extend(_emit_row_constants(parsed_headers, row, table, text))
            # Keep headers for a possible second value row; stacked tables
            # usually alternate, so the next header-like row will replace them.

    # Skip composition / property tables that never looked symbol-keyed.
    if symbol_header_blocks == 0:
        return []
    return out

# --------------------------------------------------------------------------- #
# Property tables (row = property, column = material)
# --------------------------------------------------------------------------- #

def _clean_unit(text: str) -> Optional[str]:
    """Turn a Mathpix unit fragment into something printable."""
    unit = re.sub(r"\\mathrm\{([^}]*)\}", r"\1", text)
    unit = unit.replace("$", "").replace("~", "").replace("\\", "")
    unit = re.sub(r"\s+", "", unit).strip()
    return unit or None


def _clean_expression(text: str) -> str:
    """Strip Mathpix packaging from a temperature-dependent property cell.

    ``$\\begin{gathered} -5.145 \\mathrm{e}-08 \\mathrm{~T}^{2} \\\\ +0.085 \\end{gathered}$``
    becomes ``-5.145 e-08 T^{2} + 0.085``.
    """
    expression = text.strip().strip("$").strip()
    expression = re.sub(r"\\(?:begin|end)\{[^}]*\}", " ", expression)
    expression = expression.replace("\\\\", " ")
    expression = re.sub(r"\\mathrm\{([^}]*)\}", r"\1", expression)
    expression = expression.replace("~", " ")
    return re.sub(r"\s+", " ", expression).strip()


def _normalize_material(label: str) -> Optional[str]:
    key = re.sub(r"[\s$]+", " ", label.strip().lower()).strip()
    key = re.sub(r"\\mathrm\{([^}]*)\}", r"\1", key)
    if not key:
        return None
    return _TOOL_ALIASES.get(key) or _MATERIAL_ALIASES.get(key.replace(" ", ""))


def _split_property_label(cell: str) -> Tuple[Optional[str], Optional[str], str]:
    """Return ``(symbol_name, unit, printed_label)`` for a property row label."""
    raw = re.sub(r"\s+", " ", cell.strip())
    unit = None
    match = re.search(r"\(([^)]*)\)\s*$", raw)
    label = raw
    if match:
        unit = _clean_unit(match.group(1))
        if unit in {"-", "—", "–", ""}:
            unit = None
        label = raw[: match.start()].strip()
    key = re.sub(r"[^a-z' ]+", "", label.lower()).strip()
    name = _PROPERTY_SYMBOLS.get(key)
    if name is None:
        name = next(
            (sym for prop, sym in _PROPERTY_SYMBOLS.items() if prop in key),
            None,
        )
    return name, unit, label


def _is_property_table(table: _MarkdownTable) -> bool:
    """True for tables keyed by a property per row and a material per column."""
    if not table.headers:
        return False
    first = re.sub(r"[^a-z ]+", "", table.headers[0].lower()).strip()
    if first not in _PROPERTY_HEADERS:
        return False
    return any(_normalize_material(h) for h in table.headers[1:])


def _constants_from_property_table(table: _MarkdownTable, text: str) -> List[Constant]:
    materials = [_normalize_material(h) for h in table.headers[1:]]
    out: List[Constant] = []
    for row in table.rows:
        if not row:
            continue
        name, unit, label = _split_property_label(row[0])
        if name is None:
            continue
        for column, material in enumerate(materials, start=1):
            if material is None or column >= len(row):
                continue
            raw_value = row[column]
            if not raw_value.strip():
                continue
            temperature_dependent = bool(_TEMPERATURE_RE.search(raw_value))
            value = None if temperature_dependent else parse_number(raw_value)
            if value is None and not temperature_dependent:
                continue
            out.append(
                Constant(
                    name=name,
                    value=value,
                    unit=unit,
                    variant=material,
                    source="table",
                    table=table.table_num,
                    caption=table.caption,
                    source_line=_line_of(text, table.start),
                    raw_header=table.headers[column],
                    raw_value=raw_value,
                    category="material",
                    label=label,
                    expression=_clean_expression(raw_value) if temperature_dependent else None,
                )
            )
    return out


# --------------------------------------------------------------------------- #
# Prose extraction
# --------------------------------------------------------------------------- #

def _constants_from_prose(text: str) -> List[Constant]:
    out: List[Constant] = []
    seen: set = set()
    for m in _PROSE_CONST_RE.finditer(text):
        bridge = m.group("bridge")
        # Avoid matching equation definitions like $h = h_a + ...$.
        if "=" in bridge and "approximately" not in bridge.lower():
            # Allow "= approximately" style; skip pure equation bridges.
            if not re.search(r"approximately|approx|≈", bridge, re.I):
                continue
        name = latex_to_name(m.group("sym"))
        value = parse_number(m.group("val"))
        if name is None or value is None:
            continue
        key = (name, value)
        if key in seen:
            continue
        seen.add(key)
        out.append(
            Constant(
                name=name,
                value=value,
                source="prose",
                source_line=_line_of(text, m.start()),
                raw_header=m.group("sym").strip(),
                raw_value=m.group("val").strip(),
            )
        )
    return out


# --------------------------------------------------------------------------- #
# OCR reconciliation
# --------------------------------------------------------------------------- #

#: Characters Mathpix confuses in subscripts: ``\mu_{l0}`` is read as ``\mu_{10}``.
_CONFUSABLE = str.maketrans({"1": "l", "0": "o", "O": "o"})


def _confusion_key(name: str) -> str:
    """Fold OCR look-alikes together, so ``mu_10`` and ``mu_l0`` share a key."""
    return name.translate(_CONFUSABLE)


def reconcile_names(
    constants: List[Constant], equation_symbols: Optional[Iterable[str]]
) -> List[Constant]:
    """Repair scraped names that stage 01 misread, e.g. ``mu_10`` -> ``mu_l0``.

    A subscript ``l`` read as ``1`` gives a perfectly scraped *value* a name no
    equation uses, so it never reaches the generated functions.  A constant is
    only renamed when its own name matches no equation symbol and exactly one
    equation symbol looks identical once the look-alikes are folded together;
    the original spelling is kept in ``corrected_from`` for the report.
    """
    names = set(equation_symbols or ())
    if not names:
        return constants
    by_key: Dict[str, List[str]] = {}
    for symbol_name in names:
        by_key.setdefault(_confusion_key(symbol_name), []).append(symbol_name)

    for constant in constants:
        if constant.name in names:
            continue
        candidates = by_key.get(_confusion_key(constant.name), [])
        if len(candidates) != 1:
            continue
        constant.corrected_from, constant.name = constant.name, candidates[0]
    return constants


def extract_constants(
    text: str,
    *,
    include_prose: bool = True,
    equation_symbols: Optional[Iterable[str]] = None,
) -> List[Constant]:
    """Scrape constants from markdown tables (and optionally prose) in ``text``.

    ``equation_symbols`` (stage 02's symbol dictionary) enables the OCR name
    reconciliation described in :func:`reconcile_names`.
    """
    found: List[Constant] = []
    for table in extract_tables(text):
        found.extend(_constants_from_table(table, text))
    if include_prose:
        # Prefer table values when the same name already exists without a variant.
        table_names = {c.name for c in found if c.variant is None}
        for c in _constants_from_prose(text):
            if c.name in table_names:
                continue
            found.append(c)
    return reconcile_names(found, equation_symbols)


# --------------------------------------------------------------------------- #
# Module generation
# --------------------------------------------------------------------------- #

@dataclass
class _Organised:
    """Scraped constants grouped the way the generated module lays them out."""

    shared: Dict[str, Constant]  # model constants with no variant
    tools: Dict[str, Dict[str, Constant]]  # model constants per tool material
    materials: Dict[str, Dict[str, Constant]]  # property-table values per material
    expressions: List[Constant]  # temperature-dependent properties


def _organise(constants: List[Constant]) -> _Organised:
    """Split into shared scalars, per-tool overrides and material properties."""
    shared: Dict[str, Constant] = {}
    tools: Dict[str, Dict[str, Constant]] = {}
    materials: Dict[str, Dict[str, Constant]] = {}
    expressions: List[Constant] = []
    for c in constants:
        if not c.is_numeric:
            expressions.append(c)
        elif c.category == "material":
            materials.setdefault(c.variant or "unknown", {})[c.name] = c
        elif c.variant:
            tools.setdefault(c.variant, {})[c.name] = c
        else:
            # First occurrence wins (tables usually precede prose).
            shared.setdefault(c.name, c)
    return _Organised(shared=shared, tools=tools, materials=materials, expressions=expressions)


def _fmt_float(x: float) -> str:
    """Render a float for generated source (keep scientific where natural)."""
    if x == 0:
        return "0.0"
    ax = abs(x)
    if ax >= 1e5 or (ax < 1e-3 and ax != 0):
        return f"{x:.6g}"
    # Prefer ordinary decimals for typical model params.
    s = f"{x:.12g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s


def generate_constants_module(
    text: str,
    *,
    module_doc: str = "",
    include_prose: bool = True,
    default_tool: Optional[str] = None,
    default_delta: float = 1.5e-5,
    equation_symbols: Optional[Iterable[str]] = None,
    symbol_info: Optional[Dict[str, dict]] = None,
) -> str:
    """Build a runnable ``constants.py`` source string from document ``text``.

    Layout mirrors the hand-authored plotting helper: ``_SHARED``, ``_TOOL``,
    and ``get_constants(tool, delta)`` so generated ``eq_*`` functions can be
    called with ``**get_constants()`` (or selected keys).
    """
    constants = extract_constants(
        text, include_prose=include_prose, equation_symbols=equation_symbols
    )
    grouped = _organise(constants)
    shared, tools = grouped.shared, grouped.tools

    doc = module_doc or "Auto-generated constants scraped from the paper by ExecuSci."
    lines: List[str] = [
        f'"""{doc}',
        "",
        "Names match symbols in the companion equations module (e.g. ``lamda``,",
        "``sigma_U``). Tool-specific values are grouped under ``_TOOL``, material",
        "property-table values under ``_MATERIAL``, and every name also exists as",
        "a SymPy symbol in ``SYMBOLS`` for substitution into symbolic equations.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Dict, List, Optional",
        "",
        "import sympy as sp",
        "",
        "# Shared blank / lubricant / model parameters (independent of tool material).",
        "_SHARED = {",
    ]

    for name in sorted(shared):
        c = shared[name]
        comment_bits = []
        if c.unit:
            comment_bits.append(c.unit)
        if c.table:
            comment_bits.append(f"Table {c.table}")
        elif c.source == "prose":
            comment_bits.append("prose")
        comment = f"  # {' — '.join(comment_bits)}" if comment_bits else ""
        lines.append(f'    "{name}": {_fmt_float(c.value)},{comment}')
    lines.append("}")
    lines.append("")

    lines.append("# Tool thermal conductivity and roughness by material.")
    lines.append("_TOOL = {")
    for tool in sorted(tools):
        lines.append(f'    "{tool}": {{')
        for name in sorted(tools[tool]):
            c = tools[tool][name]
            comment = f"  # Table {c.table}" if c.table else ""
            lines.append(f'        "{name}": {_fmt_float(c.value)},{comment}')
        lines.append("    },")
    lines.append("}")
    lines.append("")

    lines.append("# Thermophysical properties of each material, as printed by the paper.")
    lines.append("_MATERIAL = {")
    for material in sorted(grouped.materials):
        lines.append(f'    "{material}": {{')
        for name in sorted(grouped.materials[material]):
            c = grouped.materials[material][name]
            bits = [b for b in (c.label, c.unit, f"Table {c.table}" if c.table else None) if b]
            comment = f"  # {' — '.join(bits)}" if bits else ""
            lines.append(f'        "{name}": {_fmt_float(c.value)},{comment}')
        lines.append("    },")
    lines.append("}")
    lines.append("")

    if grouped.expressions:
        lines.append("# Properties the paper gives as functions of temperature T (in K).")
        lines.append("# They are not constants, so they are kept as the paper's expressions")
        lines.append("# rather than being turned into numbers.")
        lines.append("TEMPERATURE_DEPENDENT = {")
        for c in grouped.expressions:
            key = json.dumps(f"{c.variant}.{c.name}")
            expression = json.dumps(c.expression or "")
            label = f"  # {c.label}" if c.label else ""
            lines.append(f"    {key}: {expression},{label}")
        lines.append("}")
        lines.append("")

    if default_tool is None:
        # A paper that quotes no per-tool values has no default tool at all.
        default_tool = "P20" if "P20" in tools else next(iter(sorted(tools)), None)

    info = symbol_info if symbol_info is not None else _load_equation_symbols()
    operating = _operating_input_names(constants, info)
    if len(operating) == 1:
        operating_src = f'OPERATING_INPUTS = ("{operating[0]}",)'
    elif operating:
        operating_src = (
            "OPERATING_INPUTS = ("
            + ", ".join(f'"{n}"' for n in operating)
            + ")"
        )
    else:
        operating_src = "OPERATING_INPUTS = ()"

    lines.extend(
        [
            f'DEFAULT_TOOL = "{default_tool}"' if default_tool else "DEFAULT_TOOL = None",
            f"DEFAULT_DELTA = {_fmt_float(default_delta)}  # m — lubricant film thickness (user-supplied)",
            "",
            "# Equation inputs the paper does not tabulate (pressure, time, …).",
            "# Pass these when calling the generated eq_* functions.",
            operating_src,
            "",
            "# One SymPy symbol per scraped constant; the names are the ones the",
            "# generated equations use, so ``expr.subs(subs_map())`` just works.",
            "SYMBOLS: Dict[str, sp.Symbol] = {",
            "    name: sp.Symbol(name)",
            "    for name in sorted(",
            "        {*_SHARED, *(n for vals in _TOOL.values() for n in vals),",
            '         *(n for vals in _MATERIAL.values() for n in vals), "delta"}',
            "    )",
            "}",
            "",
            "",
            "def available_tools() -> List[str]:",
            '    """Tool materials the paper gives IHTC model constants for."""',
            "    return list(_TOOL.keys())",
            "",
            "",
            "def available_materials() -> List[str]:",
            '    """Materials the paper gives thermophysical properties for."""',
            "    return list(_MATERIAL.keys())",
            "",
            "",
            "def get_constants(tool: Optional[str] = DEFAULT_TOOL, delta: float = DEFAULT_DELTA) -> Dict[str, float]:",
            '    """Return a flat constant dict, per tool material where the paper gives one."""',
            "    if not _TOOL:",
            "        # This paper states no tool-specific values, so there is nothing to select.",
            '        return {**_SHARED, "delta": float(delta)}',
            "    if tool not in _TOOL:",
            "        raise ValueError(",
            '            f"Unknown tool {tool!r}. Choose from: {\', \'.join(available_tools())}"',
            "        )",
            '    consts = {**_SHARED, **_TOOL[tool], "delta": float(delta)}',
            "    return consts",
            "",
            "",
            "def material_properties(material: str) -> Dict[str, float]:",
            '    """Thermophysical properties (``E``, ``rho``, ``k``, …) of one material."""',
            "    if not _MATERIAL:",
            '        raise ValueError("This paper states no material property table")',
            "    if material not in _MATERIAL:",
            "        raise ValueError(",
            '            f"Unknown material {material!r}. Choose from: "',
            '            f"{\', \'.join(available_materials())}"',
            "        )",
            "    return dict(_MATERIAL[material])",
            "",
            "",
            "def symbol(name: str) -> sp.Symbol:",
            '    """The SymPy symbol scraped for ``name`` (e.g. ``symbol("k_s")``)."""',
            "    if name not in SYMBOLS:",
            "        raise KeyError(f\"No constant named {name!r} was scraped from the paper\")",
            "    return SYMBOLS[name]",
            "",
            "",
            "def subs_map(tool: Optional[str] = DEFAULT_TOOL, delta: float = DEFAULT_DELTA) -> Dict[sp.Symbol, float]:",
            '    """``{Symbol: value}`` substitution map for SymPy expressions."""',
            "    return {SYMBOLS[name]: float(value) for name, value in get_constants(tool, delta).items()}",
            "",
            "",
            "def as_dict() -> Dict[str, float]:",
            '    """All shared constants plus every tool-qualified name (``k_t_H13``, …)."""',
            "    out = {k: float(v) for k, v in _SHARED.items()}",
            "    for tool, vals in _TOOL.items():",
            '        for name, value in vals.items():',
            '            out[f"{name}_{tool}"] = float(value)',
            "    return out",
            "",
        ]
    )
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Report
# --------------------------------------------------------------------------- #

def _load_equation_symbols() -> Dict[str, dict]:
    """Symbol dictionary written by stage 02, or ``{}`` if it has not run."""
    path = os.path.join(stage_dir("Extract Equations"), "output", "symbols.json")
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh).get("symbols", {})
    except (OSError, ValueError):
        return {}


def _classify_symbol(
    name: str, info: dict, hits: Sequence[Constant]
) -> str:
    """``parameter``, ``material``, ``operating``, ``other``, or ``derived``."""
    if info.get("kind") == "derived":
        return "derived"
    if info.get("kind") == "parameter":
        return "parameter"
    if any(c.category == "material" for c in hits) or name in _MATERIAL_NAMES:
        return "material"
    description = info.get("description") or ""
    if name in _OPERATING_NAMES or _OPERATING_DESC_RE.search(description):
        return "operating"
    return "other"


def _operating_input_names(
    constants: Sequence[Constant], symbol_info: Dict[str, dict]
) -> List[str]:
    """Operating equation inputs the paper does not tabulate as numbers."""
    by_name: Dict[str, List[Constant]] = {}
    for constant in constants:
        by_name.setdefault(constant.name, []).append(constant)
    names: List[str] = []
    for name, info in sorted(symbol_info.items()):
        hits = by_name.get(name, [])
        if _classify_symbol(name, info, hits) != "operating":
            continue
        if any(c.is_numeric for c in hits):
            continue
        names.append(name)
    return names


def _fmt_value(value: Optional[float]) -> str:
    return "—" if value is None else f"{value:g}"


def generate_report(
    text: str,
    source: str = "",
    include_prose: bool = True,
    equation_symbols: Optional[Iterable[str]] = None,
    symbol_info: Optional[Dict[str, dict]] = None,
) -> str:
    """Render ``constants.md``: what was scraped, from where, and what is missing."""
    constants = extract_constants(
        text, include_prose=include_prose, equation_symbols=equation_symbols
    )
    grouped = _organise(constants)
    name = os.path.basename(source) or "the source document"
    corrected = [c for c in constants if c.corrected_from]

    lines: List[str] = [
        f"# Constants scraped from `{name}`",
        "",
        "Generated by ExecuSci stage 03 (`scrape_constants.py`). Do not edit by hand.",
        "",
        f"- Model constants and parameters: **{len(grouped.shared)}** shared, "
        f"**{sum(len(v) for v in grouped.tools.values())}** tool-specific",
        f"- Material properties: **{sum(len(v) for v in grouped.materials.values())}** "
        f"across {len(grouped.materials)} material(s)",
        f"- Temperature-dependent properties (left as expressions): "
        f"**{len(grouped.expressions)}**",
    ]
    if corrected:
        lines.append(
            f"- Names repaired after an OCR misread: **{len(corrected)}** "
            f"({', '.join(f'`{c.corrected_from}` -> `{c.name}`' for c in corrected)})"
        )
    lines.extend(
        [
            "",
            "## Model constants and parameters",
            "",
            "| Symbol | Name | Value | Unit | Tool | Source |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )

    model = [c for c in constants if c.category == "model"]
    for c in sorted(model, key=lambda c: (c.name.lower(), c.variant or "")):
        source_bits = f"Table {c.table}" if c.table else c.source
        if c.source_line:
            source_bits += f" (line {c.source_line})"
        if c.corrected_from:
            source_bits += f", read as `{c.corrected_from}`"
        lines.append(
            f"| ${name_to_latex(c.name)}$ | `{c.name}` | {_fmt_value(c.value)} "
            f"| {c.unit or '—'} | {c.variant or '—'} | {source_bits} |"
        )

    lines.extend(["", "## Material properties", ""])
    if grouped.materials:
        lines.extend(
            [
                "| Material | Property | Symbol | Name | Value | Unit | Source |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for material in sorted(grouped.materials):
            for key in sorted(grouped.materials[material]):
                c = grouped.materials[material][key]
                lines.append(
                    f"| {material} | {c.label or '—'} | ${name_to_latex(c.name)}$ "
                    f"| `{c.name}` | {_fmt_value(c.value)} | {c.unit or '—'} "
                    f"| Table {c.table} |"
                )
    else:
        lines.append("None found.")

    if grouped.expressions:
        lines.extend(
            [
                "",
                "## Temperature-dependent properties",
                "",
                "These are functions of temperature `T` (in K), not constants, so the "
                "paper's expression is kept instead of a number.",
                "",
                "| Material | Property | Expression | Unit | Source |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for c in grouped.expressions:
            expression = (c.expression or "").replace("|", "\\|")
            lines.append(
                f"| {c.variant} | {c.label or c.name} | {expression} "
                f"| {c.unit or '—'} | Table {c.table} |"
            )

    info = symbol_info if symbol_info is not None else _load_equation_symbols()
    if info:
        by_name: Dict[str, List[Constant]] = {}
        for constant in constants:
            by_name.setdefault(constant.name, []).append(constant)
        buckets: Dict[str, List[Tuple[str, dict, List[Constant]]]] = {
            "parameter": [],
            "material": [],
            "operating": [],
            "other": [],
        }
        for symbol_name, symbol in sorted(info.items()):
            bucket = _classify_symbol(
                symbol_name, symbol, by_name.get(symbol_name, [])
            )
            if bucket == "derived" or bucket not in buckets:
                continue
            buckets[bucket].append(
                (symbol_name, symbol, by_name.get(symbol_name, []))
            )

        lines.extend(
            [
                "",
                "## Coverage of the equation symbols",
                "",
                "Every symbol stage 02 found in the equations that is not itself "
                "computed by an equation, split into model parameters, material "
                "properties, and operating inputs (pressure, time, film thickness, …).",
            ]
        )
        sections = (
            (
                "parameter",
                "### Model parameters",
                "Fitted model parameters named in the paper's where-clauses.",
            ),
            (
                "material",
                "### Material properties",
                "Thermophysical or contact-body properties (tables or conventional names).",
            ),
            (
                "operating",
                "### Operating inputs",
                "Caller typically supplies these: contact pressure, time, temperature, "
                "speed, lubricant thickness.",
            ),
            (
                "other",
                "### Other inputs",
                "Remaining equation inputs that are not parameters, properties, or "
                "operating conditions.",
            ),
        )
        for key, heading, blurb in sections:
            rows = buckets[key]
            if key == "other" and not rows:
                continue
            lines.extend(["", heading, "", blurb, ""])
            if not rows:
                lines.append("None found.")
                continue
            lines.extend(
                [
                    "| Name | Needed by | Scraped value | Where |",
                    "| --- | --- | --- | --- |",
                ]
            )
            for symbol_name, symbol, hits in rows:
                used_in = ", ".join(symbol.get("used_in") or []) or "—"
                if not hits:
                    lines.append(
                        f"| `{symbol_name}` | {used_in} | — | supplied by caller |"
                    )
                    continue
                values = ", ".join(
                    f"{_fmt_value(c.value) if c.is_numeric else 'f(T)'}"
                    f"{f' ({c.variant})' if c.variant else ''}"
                    for c in hits
                )
                where = ", ".join(
                    sorted(
                        {
                            f"Table {c.table}" if c.table else c.source
                            for c in hits
                        }
                    )
                )
                lines.append(
                    f"| `{symbol_name}` | {used_in} | {values} | {where} |"
                )

    lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #

def run(
    paper: Optional[str] = None,
    constants_path: str = DEFAULT_CONSTANTS_PATH,
    report_path: str = DEFAULT_REPORT_PATH,
    include_prose: bool = True,
    verbose: bool = True,
) -> List[Constant]:
    """Scrape ``paper`` and write ``constants.py`` and ``constants.md``."""
    path = paper or paper_path()
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()

    # Stage 02 knows how the equations spell each symbol, which is what lets an
    # OCR-damaged table header be matched back to the symbol it was meant to be.
    equation_info = _load_equation_symbols()
    equation_symbols = set(equation_info)

    constants = extract_constants(
        text, include_prose=include_prose, equation_symbols=equation_symbols
    )
    source = generate_constants_module(
        text,
        module_doc=f"Constants scraped from {os.path.basename(path)}.",
        include_prose=include_prose,
        equation_symbols=equation_symbols,
        symbol_info=equation_info,
    )
    os.makedirs(os.path.dirname(os.path.abspath(constants_path)), exist_ok=True)
    os.makedirs(os.path.dirname(os.path.abspath(report_path)), exist_ok=True)
    with open(constants_path, "w", encoding="utf-8") as fh:
        fh.write(source)
    with open(report_path, "w", encoding="utf-8") as fh:
        fh.write(
            generate_report(
                text,
                source=path,
                include_prose=include_prose,
                equation_symbols=equation_symbols,
                symbol_info=equation_info,
            )
        )
    mirror_to_log(constants_path)

    if verbose:
        grouped = _organise(constants)
        print(f"Read {os.path.basename(path)}")
        print(
            f"  {len(grouped.shared)} shared constants, "
            f"{sum(len(v) for v in grouped.tools.values())} tool-specific, "
            f"{sum(len(v) for v in grouped.materials.values())} material properties"
        )
        if grouped.expressions:
            print(
                f"  {len(grouped.expressions)} temperature-dependent properties "
                "kept as expressions"
            )
        corrected = [c for c in constants if c.corrected_from]
        if corrected:
            print(
                "  repaired OCR-damaged names: "
                + ", ".join(f"{c.corrected_from} -> {c.name}" for c in corrected)
            )
        print(f"  wrote {constants_path}")
        print(f"  wrote {report_path}")

    return constants


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scrape the paper's constants and name them with SymPy symbols."
    )
    parser.add_argument(
        "--paper",
        default=None,
        help="Markdown/LaTeX source (default: the file in src/01_input/target/)",
    )
    parser.add_argument(
        "--constants",
        default=DEFAULT_CONSTANTS_PATH,
        help=f"Generated module path (default: {DEFAULT_CONSTANTS_PATH})",
    )
    parser.add_argument(
        "--report",
        default=DEFAULT_REPORT_PATH,
        help=f"Generated markdown report path (default: {DEFAULT_REPORT_PATH})",
    )
    parser.add_argument(
        "--no-prose",
        action="store_true",
        help="Only scrape tables, ignoring prose such as 'approximately 0.8'.",
    )
    return parser.parse_args(list(argv) if argv is not None else None)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parse_args(argv)
    constants = run(
        paper=args.paper,
        constants_path=args.constants,
        report_path=args.report,
        include_prose=not args.no_prose,
    )
    return 0 if constants else 1


if __name__ == "__main__":
    raise SystemExit(main())
